name: couldai_user_app
# A password manager Flutter application
description: "A Flutter password manager app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1

  # 本地数据库和存储依赖
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
